server:
  port: 8081
  servlet:
    context-path: /demo
spring:
  security:
    user:
      name: pyc
      password: 123456
management:
  server:
    port: 8090
    servlet:
      context-path: /sys

  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: '*'
